// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetFilesRootRelpathParams is parameters of get-files-root-relpath operation.
type GetFilesRootRelpathParams struct {
	// Relative path to search.
	Relpath OptString
	// Id of the file root to check.
	Root int
}

func unpackGetFilesRootRelpathParams(packed middleware.Parameters) (params GetFilesRootRelpathParams) {
	{
		key := middleware.ParameterKey{
			Name: "relpath",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Relpath = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "root",
			In:   "path",
		}
		params.Root = packed[key].(int)
	}
	return params
}

func decodeGetFilesRootRelpathParams(args [1]string, argsEscaped bool, r *http.Request) (params GetFilesRootRelpathParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: relpath.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "relpath",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRelpathVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRelpathVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Relpath.SetTo(paramsDotRelpathVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "relpath",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: root.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "root",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.Root = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
				}).Validate(int64(params.Root)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "root",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
