// Code generated by ogen, DO NOT EDIT.
package api

type GetFilesRootRelpathRes interface {
	getFilesRootRelpathRes()
}

type GetStatusRes interface {
	getStatusRes()
}

type PlayerStartPostRes interface {
	playerStartPostRes()
}
